version: '3.8'

services:
  # FastAPI App Instance 1
  fastapi-app-1:
    container_name: fastapi_app_instance_1
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - INSTANCE_ID=instance_1
      - INSTANCE_NAME=FastAPI-App-1
    ports:
      - "8001:8000"
    networks:
      - llm-monitor
      - monitoring

  # FastAPI App Instance 2
  fastapi-app-2:
    container_name: fastapi_app_instance_2
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - INSTANCE_ID=instance_2
      - INSTANCE_NAME=FastAPI-App-2
    ports:
      - "8002:8000"
    networks:
      - llm-monitor
      - monitoring

networks:
  llm-monitor:
    driver: bridge
  monitoring:
    external: true

volumes:
  mlflow_db_data: