# QA Chatbot Application Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
    component: api
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
      component: api
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        component: api
    spec:
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
      - name: qa-chatbot
        image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
        imagePullPolicy: {{ .Values.app.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        env:
        {{- range .Values.app.env }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        {{- if .Values.app.envFile }}
        envFrom:
        - configMapRef:
            name: {{ .Values.app.name }}-env-config
        {{- end }}
        resources:
          {{- toYaml .Values.app.resources | nindent 12 }}
        livenessProbe:
          {{- toYaml .Values.app.livenessProbe | nindent 12 }}
        readinessProbe:
          {{- toYaml .Values.app.readinessProbe | nindent 12 }}


      {{- if .Values.persistence.enabled }}
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: {{ include "multi-agent-microservices.fullname" . }}-pvc
      {{- end }}
