# QA Chatbot Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
    component: api
spec:
  type: {{ .Values.app.service.type }}
  ports:
  {{- range .Values.app.service.ports }}
  - name: {{ .name }}
    port: {{ .port }}
    targetPort: {{ .targetPort }}
    protocol: TCP
  {{- end }}
  selector:
    app: {{ .Values.app.name }}
    component: api


