# QA Chatbot Stack Configuration
app:
  name: qa-chatbot
  replicaCount: 2

  image:
    repository: qa-chatbot
    pullPolicy: IfNotPresent
    tag: "latest"

  service:
    type: ClusterIP
    ports:
      - name: app-1
        port: 8001
        targetPort: 8000
      - name: app-2
        port: 8002
        targetPort: 8000

  env:
    - name: PORT
      value: "8000"
    - name: LOG_LEVEL
      value: "INFO"
    - name: DEBUG
      value: "false"
    # S3 and Model configs will be loaded from envFile

  # Environment file path (will be set by Jenkins)
  envFile: ""

  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi

  livenessProbe:
    httpGet:
      path: /health
      port: 8000
    initialDelaySeconds: 30
    periodSeconds: 10

  readinessProbe:
    httpGet:
      path: /health
      port: 8000
    initialDelaySeconds: 5
    periodSeconds: 5

# Ingress Configuration
ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: qa-chatbot.local
      paths:
        - path: /
          pathType: Prefix
          service: qa-chatbot
  tls: []

# Security Context
securityContext:
  runAsNonRoot: true
  runAsUser: 1000

# Health checks
healthCheck:
  enabled: true
  path: /health
  initialDelaySeconds: 30
  periodSeconds: 10
